// Code generated by mockery v1.0.0. DO NOT EDIT.

package bridge

import mock "github.com/stretchr/testify/mock"
import model "github.com/pagient/pagient-server/internal/bridge/model"

// MockTx is an autogenerated mock type for the Tx type
type MockTx struct {
	mock.Mock
}

// Commit provides a mock function with given fields:
func (_m *MockTx) Commit() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRoomAssignments provides a mock function with given fields: _a0, _a1
func (_m *MockTx) GetRoomAssignments(_a0 string, _a1 ...uint) ([]*model.RoomAssignment, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 []*model.RoomAssignment
	if rf, ok := ret.Get(0).(func(string, ...uint) []*model.RoomAssignment); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RoomAssignment)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...uint) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Rollback provides a mock function with given fields:
func (_m *MockTx) Rollback() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
