// Code generated by mockery v1.0.0. DO NOT EDIT.

package caller

import mock "github.com/stretchr/testify/mock"
import model "github.com/pagient/pagient-server/internal/model"

// MockSoftwareBridge is an autogenerated mock type for the SoftwareBridge type
type MockSoftwareBridge struct {
	mock.Mock
}

// GetExaminedPatients provides a mock function with given fields:
func (_m *MockSoftwareBridge) GetExaminedPatients() ([]*model.Patient, error) {
	ret := _m.Called()

	var r0 []*model.Patient
	if rf, ok := ret.Get(0).(func() []*model.Patient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Patient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetToBeExaminedPatients provides a mock function with given fields:
func (_m *MockSoftwareBridge) GetToBeExaminedPatients() ([]*model.Patient, error) {
	ret := _m.Called()

	var r0 []*model.Patient
	if rf, ok := ret.Get(0).(func() []*model.Patient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Patient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
