// Code generated by mockery v1.0.0. DO NOT EDIT.

package service

import mock "github.com/stretchr/testify/mock"

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

// Begin provides a mock function with given fields:
func (_m *MockDB) Begin() (Tx, error) {
	ret := _m.Called()

	var r0 Tx
	if rf, ok := ret.Get(0).(func() Tx); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Tx)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
